name: Package Scripts
on: push
jobs:
  scripts:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install modules
        run: yarn
      - name: Deploy
        run: printf 'y\n' | yarn deploy
      - name: Start
        timeout-minutes: 1
        run: yarn start